image: docker/compose:1.25.0-rc4

variables:
  DOMAIN: marroquin.dev

.job_variables: &variables
  only:
    - master
  tags:
    - production
  when: manual

portainer:
  <<: *variables
  environment:
    name: portainer
    url: https://portainer.${DOMAIN}
  script:
    - docker-compose --project-name portainer -f docker-portainer.yml up -d --force-recreate --remove-orphans

netdata:
  environment:
    name: netdata
    url: https://netdata.${DOMAIN}
  script:
    - docker-compose --project-name netdata -f docker-netdata.yml up -d --force-recreate --remove-orphans
