image: tmaier/docker-compose:latest

stages:
  - deployment

variables:
  URL_NAME: wordpress
  PROJECT_NAME: wordpress_example
  BASE_URL: marroquin.dev
  USER_EMAIL: luis@marroquin.dev
  # Dont edit the following
  APP_PORT: 80
  DB_PORT: 80

deploy:
  stage: deployment
  script:
    - echo 'Deploying Production'
    - docker-compose --project-name ${PROJECT_NAME}_prod --file docker-compose.yml up -d --build --force-recreate --remove-orphans
  environment:
    name: Production
    url: https://${URL_NAME}.${BASE_URL}
    on_stop: stop
  only:
    - master
  tags:
    - env-production

stop:
  stage: deployment
  when: manual
  script:
    - echo 'Stopping Production'
    - docker-compose --project-name ${PROJECT_NAME}_prod --file docker-compose.yml stop
  environment:
    name: Production
    action: stop
  only:
    - master
  tags:
    - env-production
