image: docker/compose:latest

.variables_compose: &compose
  variables:
    DOMAIN: marroquin.dev
  only:
    - main
  tags:
    - production
  when: manual

netdata-compose:
  <<: *compose
  environment:
    name: netdata
    url: https://netdata.${DOMAIN}
  script:
    - docker-compose -p netdata -f docker-netdata.yml up -d --force-recreate --remove-orphans

nginx-compose:
  <<: *compose
  environment:
    name: nginx
    url: https://whoami.${DOMAIN}
  script:
    - docker-compose -p nginx -f docker-compose.yml up -d --force-recreate --remove-orphans

portainer-compose:
  <<: *compose
  environment:
    name: portainer
    url: https://portainer.${DOMAIN}
  script:
    - docker-compose -p portainer -f docker-portainer.yml up -d --force-recreate --remove-orphans

whoami-compose:
  <<: *compose
  environment:
    name: nginx
    url: https://whoami.${DOMAIN}
  script:
    - docker-compose -p whoami -f docker-whoami.yml up -d --force-recreate --remove-orphans

wordpress-compose:
  <<: *compose
  environment:
    name: wordpress
    url: https://wordpress.${DOMAIN}
  script:
    - docker-compose -p wordpress -f docker-wordpress.yml up -d --force-recreate --remove-orphans
