image: tmaier/docker-compose:latest

stages:
  - deployment

variables:
  PROJECT_NAME: wordpress
  BASE_URL: wordpress.marroquin.dev
  USER_EMAIL: luis@marroquin.dev
  # Dont edit the following
  APP_PORT: 80
  DB_PORT: 9000

deploy:
  stage: deployment
  script:
    - echo 'Deploying Production'
    - docker-compose --project-name ${PROJECT_NAME}_master --file docker-compose.yml up -d --build --force-recreate --remove-orphans
  environment:
    name: Production
    url: https://${BASE_URL}
    on_stop: stop
  only:
    - master
  tags:
    - production

stop:
  stage: deployment
  when: manual
  script:
    - echo 'Stopping Production'
    - docker-compose --project-name ${PROJECT_NAME}_master --file docker-compose.yml stop
  environment:
    name: Production
    action: stop
  only:
    - master
  tags:
    - production
