image: docker/compose:1.25.0-rc4

variables:
  PRO_NAME: code
  FULL_URL: code.marroquin.dev

.variables: &deploy_variables
  stage: deploy
  only:
    - master
  tags:
    - production
deploy:
  <<: *deploy_variables
  script:
    - docker-compose --project-name ${PRO_NAME} up -d --build --force-recreate --remove-orphans
  environment:
    name: master
    url: https://${FULL_URL}
    on_stop: stop
  when: manual
stop:
  <<: *deploy_variables
  script:
    - docker-compose --project-name ${PRO_NAME} stop
  environment:
    name: master
    action: stop
