version: '3.7'

volumes:
  redis:

services:
  python:
    build:
      context: .
      dockerfile: build/python.Dockerfile
    container_name: python
    environment:
      VIRTUAL_HOST: python.${DOMAIN}
      LETSENCRYPT_HOST: python.${DOMAIN}
    ports:
      - 5000
  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - redis:/data
