version: '3.3'

networks:
  default:
    external:
      name: nginx-proxy
  internal:
    internal: true

volumes:
  db_data: {}

services:
  db: # M1
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      internal:
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${db}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${pass}
      MYSQL_ROOT_PASSWORD: ${root}
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${APP_PORT:-8000:80}
    networks:
      default: {}
      internal:
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: ${db}
      WORDPRESS_DB_HOST: db # Database service name
      WORDPRESS_DB_USER: ${user}
      WORDPRESS_DB_PASSWORD: ${pass}
      
      # Nginx SSL Proxy
      VIRTUAL_HOST: ${URL_NAME}.${BASE_URL}
      LETSENCRYPT_HOST: ${URL_NAME}.${BASE_URL}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-9000:80}
    networks:
      default: {}
      internal:
    environment:
      PMA_HOST: db:3306
      PMA_ARBITRARY: 1
      # Manual login
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${pass}
      MYSQL_ROOT_PASSWORD: ${root}
      # Auto login
      # PMA_USER: ${user}
      # PMA_PASSWORD: ${pass}
      # Nginx SSL Proxy
      VIRTUAL_HOST: db.${URL_NAME}.${BASE_URL}
      LETSENCRYPT_HOST: db.${URL_NAME}.${BASE_URL}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
