version: "3.7"

networks:
  external:
    name: nginx-proxy

services:
  wetty:
    container_name: wetty
    environment:
      VIRTUAL_HOST: wetty.${DOMAIN}
      LETSENCRYPT_HOST: wetty.${DOMAIN}
    image: krishnasrinivas/wetty
    networks:
      - external
    ports:
      - 3000:3000
    restart: unless-stopped
