version: '3.7'

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  data:
  project:
  projects:

services:
  codeserver:
    build: .
    command: code-server --no-auth # if using proxy add: --allow-http
    container_name: code
    environment:
      LETSENCRYPT_EMAIL: ${MY_EMAIL}
      LETSENCRYPT_HOST: ${FULL_URL}
      VIRTUAL_HOST: ${FULL_URL}
    ports:
      - 8443
    restart: unless-stopped
    volumes:
      - data:/data
      - project:/home/coder/project
      - projects:/root/projects
