version: "3.7"

volumes:
  mongo:
  mongoc:

services:
  mongo:
    container_name: mongo
    image: mongo:4.0.3 # Lastest licensed as AGPLv3
    volumes:
      - mongo:/data/db
      - mongoc:/data/configdb
  node:
    build:
      context: .
      dockerfile: build/node.Dockerfile
    container_name: node
    depends_on:
      - mongo
    environment:
      PRODUCTION: "true"
  nginx:
    build:
      context: .
      dockerfile: build/nginx.Dockerfile
    container_name: nginx
    depends_on:
      - node
    ports:
      - 80:80
