version: '3.7'

networks:
  external:
    name: nginx-proxy
  internal:
    internal: true

volumes:
  mysql:
  wordpress:

services:
  mysql: # Database service name
    environment:
      MYSQL_USER: ${user}
      MYSQL_DATABASE: ${db}
      MYSQL_PASSWORD: ${pass}
      MYSQL_ROOT_PASSWORD: ${root}
    image: mysql:5.7
    networks:
      - internal
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - ${WP_PORT:-8000:80}
    networks:
      - external
      - internal
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: ${db}
      WORDPRESS_DB_HOST: mysql # Database service name
      WORDPRESS_DB_USER: ${user}
      WORDPRESS_DB_PASSWORD: ${pass}
      # Nginx SSL Proxy
      VIRTUAL_HOST: ${BRANCHES}.${MAIN_URL}.${BASE_URL}
      LETSENCRYPT_HOST: ${BRANCHES}.${MAIN_URL}.${BASE_URL}
      LETSENCRYPT_EMAIL: ${MY_EMAIL}
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    depends_on:
      - mysql
      - wordpress
    environment:
      PMA_HOST: mysql:3306 # Database service name : database port
      PMA_ARBITRARY: 1 # This will run phpMyAdmin with arbitrary server - allowing you to specify MySQL/MariaDB server on login page.
      # Manual login
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${pass}
      MYSQL_ROOT_PASSWORD: ${root}
      # Nginx SSL Proxy
      VIRTUAL_HOST: db.${BRANCHES}.${MAIN_URL}.${BASE_URL}
      LETSENCRYPT_HOST: db.${BRANCHES}.${MAIN_URL}.${BASE_URL}
      LETSENCRYPT_EMAIL: ${MY_EMAIL}
      # Auto login
      # PMA_USER: ${user}
      # PMA_PASSWORD: ${pass}
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - external
      - internal
    ports:
      - ${DB_PORT:-9000:80}
    restart: unless-stopped
