version: '3.7'

networks:
  external:
    name: nginx-proxy
  internal:
    internal: true

volumes:
  mysql:
  wordpress:

services:
  mysql: # Database service name
    environment:
      MYSQL_USER: ${WP_USER:-admin}
      MYSQL_DATABASE: ${WP_DATABASE:-default_db}
      MYSQL_PASSWORD: ${WP_PASS:-12345678}
      MYSQL_ROOT_PASSWORD: ${WP_ROOT:-root_pass}
    image: mysql:5.7
    networks:
      - internal
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 8000
    networks:
      - external
      - internal
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: ${WP_DATABASE:-default_db}
      WORDPRESS_DB_HOST: mysql # Database service name
      WORDPRESS_DB_USER: ${WP_USER:-admin}
      WORDPRESS_DB_PASSWORD: ${WP_PASS:-12345678}
      VIRTUAL_HOST: wordpress.${DOMAIN}
      LETSENCRYPT_HOST: wordpress.${DOMAIN}
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    depends_on:
      - wordpress
    environment:
      PMA_HOST: mysql:3306 # Database service name : database port
      PMA_ARBITRARY: 1 # This will run phpMyAdmin with arbitrary server - allowing you to specify MySQL/MariaDB server on login page
      MYSQL_USER: ${WP_USER:-admin}
      MYSQL_PASSWORD: ${WP_PASS:-12345678}
      MYSQL_ROOT_PASSWORD: ${WP_ROOT:-root_pass}
      VIRTUAL_HOST: db.wordpress.${DOMAIN}
      LETSENCRYPT_HOST: db.wordpress.${DOMAIN}
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - external
      - internal
    ports:
      - 9000
    restart: unless-stopped
