version: '3.7'

networks:
  default:
    external:
      name: nginx-proxy

services:
  codeserver:
    command: code-server # if no auth add: --no-auth # if using proxy add: --allow-http
    container_name: code
    environment:
      LETSENCRYPT_EMAIL: ${MY_EMAIL}
      LETSENCRYPT_HOST: ${FULL_URL}
      PASSWORD: ${PASSWORD}
      VIRTUAL_HOST: ${FULL_URL}
    image: codercom/code-server
    ports:
      - 8443
    restart: unless-stopped
    volumes:
      - /root/code/data:/data
      - /root/code/projects:/root/projects
